# Generated by Django 3.1 on 2020-08-25 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VulnTrends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.SmallIntegerField()),
                ('nr_vuln', models.SmallIntegerField()),
                ('dos', models.SmallIntegerField()),
                ('code_exec', models.SmallIntegerField()),
                ('overflow', models.SmallIntegerField()),
                ('memory_cor', models.SmallIntegerField()),
                ('sql_injection', models.SmallIntegerField()),
                ('xss', models.SmallIntegerField()),
                ('Directory', models.SmallIntegerField()),
                ('http_resp', models.SmallIntegerField()),
                ('bypass', models.SmallIntegerField()),
                ('gain_info', models.SmallIntegerField()),
                ('gain_priv', models.SmallIntegerField()),
                ('csrf', models.SmallIntegerField()),
                ('exploits', models.SmallIntegerField()),
            ],
        ),
    ]
